pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/dgeniust/hcmute-care.git', branch: 'deploy/set-up-jenkins-v1'
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('backend') { 
                    script {
                        sh 'docker build -t utecare-backend:latest .'
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                dir('backend') { 
                    script {
                        sh 'docker-compose -f /var/jenkins_home/workspace/UTECare-Backend-Pipeline/backend/docker-compose.yml down backend-service'
                        sh 'docker-compose -f /var/jenkins_home/workspace/UTECare-Backend-Pipeline/backend/docker-compose.yml up -d backend-service'
                    }
                }
            }
        }
    }
    post {
        success {
            echo 'Build and deployment successful!'
        }
        failure {
            dir('backend') {
                script {
                    echo 'Build failed, cleaning up resources...'
                    sh 'docker rmi utecare-backend:latest || true'
                    sh 'docker image prune -f || true'
                }
            }
        }
        always {
            echo 'Pipeline completed.'
        }
    }
}