spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}?useSSL=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
jwt:
  accessToken:
    secretKey: ${JWT_ACCESS_TOKEN_SECRET_KEY}
    expiry: ${JWT_ACCESS_TOKEN_EXPIRY}
  refreshToken:
    secretKey: ${JWT_REFRESH_TOKEN_SECRET_KEY}
    expiry: ${JWT_REFRESH_TOKEN_EXPIRY}
  verificationToken:
    secretKey: ${JWT_VERIFICATION_TOKEN_SECRET_KEY}
    expiry: ${JWT_VERIFICATION_TOKEN_EXPIRY}
  resetToken:
    secretKey: ${JWT_RESET_TOKEN_SECRET_KEY}
    expiry: ${JWT_RESET_TOKEN_EXPIRY}

payment:
  vnPay:
    url: ${VNPAY_URL}
    tmnCode: ${VNPAY_TMN_CODE}
    secretKey: ${VNPAY_SECRET_KEY}
    returnUrl: ${VNPAY_RETURN_URL}
    version: 2.1.0
    command: pay
    orderType: other

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true