server:
  port: 8080

spring:
  application:
    name: UTECare
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO